version: "3"
services:
  otel-collector:
    image: images.agodadev.io/dockerhub/otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./config/otel.collector.yaml:/etc/otel/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "9464:9464" # Prometheus metrics
    networks:
      - otel

  prometheus:
    image: images.agodadev.io/dockerhub/prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel

  grafana:
    image: images.agodadev.io/dockerhub/grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - otel
    depends_on:
      - prometheus

  jaeger:
    image: images.agodadev.io/dockerhub/jaegertracing/all-in-one
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    networks:
      - otel

networks:
  otel:

volumes:
  grafana-storage:
